services:
  - type: web
    name: timebeacon-landing
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION  
        value: "20"
    domains:
      - timebeacon.io